name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

      - name: Create ZIP files
        run: |
          cd dist
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            powershell -Command "Compress-Archive -Path .\win-unpacked -DestinationPath PokeRogue-Windows.zip"
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            zip -r PokeRogue-Linux.zip linux-unpacked
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r PokeRogue-macOS.zip mac
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PokeRogue-${{ matrix.os }}
          path: |
            dist/PokeRogue-Windows.zip
            dist/PokeRogue-Linux.zip
            dist/PokeRogue-macOS.zip

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: draft
          release_name: Draft Release
          draft: true
          prerelease: false
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PokeRogue-Windows.zip
          asset_name: PokeRogue-Windows.zip
          asset_content_type: application/zip
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PokeRogue-Linux.zip
          asset_name: PokeRogue-Linux.zip
          asset_content_type: application/zip
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/PokeRogue-macOS.zip
          asset_name: PokeRogue-macOS.zip
          asset_content_type: application/zip
